### ISSUE TITLE
Error: Method WPML_TextDomain::_cb_actionPluginsLoaded() does not exist

### ISSUE THREAD

**Issue by marcissimus** [Ironikus/wp-mailto-links#1]
Hi Ironikus,

when using the plug-in several errors are thrown:

WPML_TextDomain::_cb_actionPluginsLoaded()
Error: Method WPML_TextDomain::_cb_actionPluginsLoaded() does not exist

WPRun_Filter_FinalOutput_0x5x0::_cb_actionInit()
Error: Method WPRun_Filter_FinalOutput_0x5x0::_cb_actionInit() does not exist

WPML_Front_Site::_cb_actionWp()
Error: Method WPML_Front_Site::_cb_actionWp() does not exist

WPML_Front_Site::_cb_actionWpHead()
Error: Method WPML_Front_Site::_cb_actionWpHead() does not exist

WPML_Front_Site::_cb_actionWpEnqueueScripts()
Error: Method WPML_Front_Site::_cb_actionWpEnqueueScripts() does not exist

This can be seen for example if you use the "Query Monitor" plug-in (under Requests > Hooks in Use). The issue was reported also before to the previous owner (https://github.com/freelancephp/WP-Mailto-Links/issues/21).

There seems something wrong in the WPRun / WPML framework. It would be nice if you could figure out how to avoid these errors since they are a distraction when debugging a wp site. 

Thanks!
Marc

**Comment by Ironikus** [comment]
Hi Marc, 

thank you a lot for your report! 
We are currently refactoring the whole plugin to make it more lightweight. 
I make sure that these messages are gone as well. 

All the best
Jannis

**Comment by marcissimus** [comment]
Solved after the rewrite
